import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, AlertTriangle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription } from '@/components/ui/alert';

const HealthDisclaimer = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="mb-6">
          <Link to="/auth">
            <Button variant="ghost" className="mb-4">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Login
            </Button>
          </Link>
          <h1 className="text-3xl font-bold text-primary mb-2">Health Disclaimer</h1>
          <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <Alert className="mb-6">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription className="font-semibold">
            IMPORTANT: Please read this disclaimer carefully before using MeTime.
          </AlertDescription>
        </Alert>

        <div className="space-y-6 text-foreground">
          <section>
            <h2 className="text-xl font-semibold mb-3">Medical Advice Disclaimer</h2>
            <p className="mb-3">
              <strong>MeTime is not a medical application and does not provide medical advice.</strong> The information provided by MeTime, including but not limited to wellness activities, exercise recommendations, breathing exercises, and productivity tips, is for general informational and educational purposes only.
            </p>
            <p>
              The content in this application is not intended to be a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">No Doctor-Patient Relationship</h2>
            <p>
              The use of MeTime does not create a doctor-patient relationship between you and any healthcare provider. The application's recommendations are generated by algorithms and are not personalized medical advice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Exercise and Physical Activity</h2>
            <p className="mb-3">
              Before starting any exercise program or physical activity suggested by MeTime:
            </p>
            <ul className="list-disc list-inside ml-4 space-y-1">
              <li>Consult with your doctor or healthcare provider</li>
              <li>Ensure you are physically capable of performing the activities</li>
              <li>Stop immediately if you experience pain, discomfort, or unusual symptoms</li>
              <li>Modify activities based on your fitness level and physical limitations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Pre-existing Conditions</h2>
            <p>
              If you have any pre-existing medical conditions, injuries, or take medications, consult your healthcare provider before using wellness recommendations from MeTime. This includes but is not limited to:
            </p>
            <ul className="list-disc list-inside ml-4 mt-2 space-y-1">
              <li>Heart conditions or cardiovascular disease</li>
              <li>Respiratory conditions</li>
              <li>Musculoskeletal injuries or conditions</li>
              <li>Mental health conditions</li>
              <li>Pregnancy</li>
              <li>Any chronic illness or condition</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Emergency Situations</h2>
            <p className="mb-3">
              <strong>MeTime is not designed for emergency situations.</strong> If you are experiencing a medical emergency, call emergency services immediately (911 in the US, or your local emergency number).
            </p>
            <p>
              Never ignore professional medical advice or delay seeking treatment because of information you have read in MeTime.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Individual Results May Vary</h2>
            <p>
              Results from using MeTime's wellness recommendations may vary significantly between individuals. Factors such as age, fitness level, health status, and adherence to recommendations will affect outcomes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Limitation of Liability</h2>
            <p>
              MeTime and its creators, developers, and affiliates shall not be liable for any damages, injuries, or health issues that may arise from the use of this application or following its recommendations. Use of MeTime is at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Accuracy of Information</h2>
            <p>
              While we strive to provide accurate and up-to-date information, MeTime makes no representations or warranties about the accuracy, completeness, or suitability of the health and wellness information provided.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Third-Party Content</h2>
            <p>
              MeTime may include content from third-party sources. We do not endorse or guarantee the accuracy of third-party content and are not responsible for any consequences of using such information.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Age Restrictions</h2>
            <p>
              MeTime is intended for use by adults 18 years and older. If you are under 18, please consult with a parent or guardian and healthcare provider before using this application.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Acknowledgment</h2>
            <p>
              By using MeTime, you acknowledge that you have read, understood, and agree to this Health Disclaimer. You understand that the information provided is not medical advice and that you should consult healthcare professionals for medical concerns.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Contact Information</h2>
            <p>
              If you have questions about this Health Disclaimer, please contact us at health@metime-app.com.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default HealthDisclaimer;