// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geyjigdkfbwezrzdvlaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdleWppZ2RrZmJ3ZXpyemR2bGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjExNzksImV4cCI6MjA3MDk5NzE3OX0.PZq5Nr7LXg9h55UqycQwdmCOQqAtxbNQTRa1psl6AdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});